# Login Request
POST http://127.0.0.1:8000/login/
Content-Type: application/json

{ "username": "Salah", "password": "pass1234" }

###

# Signup Request
POST http://127.0.0.1:8000/signup/
Content-Type: application/json

{"username": "Salah", "password": "pass1234", "email": "salah@gmail.com" }

####

# Test Token Request
GET http://127.0.0.1:8000/test_token/
Content-Type: application/json
Authorization: Token 40af0e1310d7897b4273a914f162e1d380d176c5

{}
