name: Django CI

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9  # or 3.8

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install Django djangorestframework

    - name: Apply Django Migrations
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install Django
        python manage.py migrate

    - name: Linting
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install flake8
        flake8 .


    - name: Run Django Tests
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install Django
        python manage.py test




